name: 'Rust musl build'
description: 'Build rust project with musl target'
author: 'arloor'

# Define your inputs here.
inputs:
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    required: true
    default: ''

# Define your outputs here.
outputs:
  release_dir:
    description: 'the dir which contain the release binary'

runs:
  using: docker
  image: Dockerfile
  env:
    CARGO_TERM_COLOR: always
    # INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}
