name: 'Rust musl build'
description: 'Build rust project with musl target'
author: 'arloor'

# Define your inputs here.
inputs:
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    required: true
    default: ''
  args:
    description: 'custom args passed to cargo build'
    required: true
    default: ''
  rust_version:
    description: 'rust version. eg: 1.76.0. default is latest'
    required: true
    default: ''
  musl_version:
    description: 'musl version. eg: 1.2.5'
    required: true
    default: '1.2.5'

# Define your outputs here.
outputs:
  release_dir:
    description: 'the dir which contain the musl release binary, NOTE: the value ends with /'

runs:
  using: docker
  image: Dockerfile
  env:
    CARGO_TERM_COLOR: always
