name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: arloor/rust_http_proxy
          path: rust_http_proxy

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          path: rust_http_proxy

      - name: Print Output
        id: output
        run: |
          echo "release_dir: ${{ steps.test-action.outputs.release_dir }}"
          ls -lh ${{ steps.test-action.outputs.release_dir }}
